# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>

development:
  <<: *default
  database: to_do_list_v360_development

test:
  <<: *default
  database: to_do_list_v360_test

production:
  primary: &primary_production
    <<: *default
    database: to_do_list_v360_production
    username: to_do_list_v360
    password: <%= ENV["DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: to_do_list_v360_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: to_do_list_v360_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: to_do_list_v360_production_cable
    migrations_paths: db/cable_migrate
